### PR TITLE
landing page overall fixes

### PR DESCRIPTION
**Pull request by IgboPharaoh**
- This PR introduces a couple of fixes for the landing page to satisfy issue #33

### CODE REVIEW

**Comment by IgboPharaoh** [comment]
- My mistake, the navbar has to be sticky, will add this change.
- I don't know of a way to fix that nit. Either text follow the natural order and wrap inside it's container or they're broken and display on multiple lines.

**Comment by IgboPharaoh** [comment]
>  except for the favicon fidelity. The favicon issue might require further discussion since the logo contains too many words to be displayed clearly in any setup.

For the favicon, I think it's a discussion we need to have with the rest of the team especially Tobi.
I tried using figma to scale the current favicon to a 16 x 16 and 4 x 4 dimension but the transcripts text still makes it blurry at that size. We might want to change the favicons we use to be high fidelity icons only.

**Comment by kouloumos** [comment]
> My mistake, the navbar has to be sticky, will add this change.

In my previous comment I said that I liked the removal of the "stickiness". But I'm okay either way. Is that specified on the designs?

>    I don't know of a way to fix that nit. Either text follow the natural order and wrap inside it's container or they're broken and display on multiple lines.

Have you tried what I suggested [here](https://github.com/bitcointranscripts/registry/pull/18#discussion_r1756363360)?

**Comment by IgboPharaoh** [comment]
> > My mistake, the navbar has to be sticky, will add this change.
> 
> In my previous comment I said that I liked the removal of the "stickiness". But I'm okay either way. Is that specified on the designs?
> 
> > I don't know of a way to fix that nit. Either text follow the natural order and wrap inside it's container or they're broken and display on multiple lines.
> 
> Have you tried what I suggested [here](https://github.com/bitcointranscripts/registry/pull/18#discussion_r1756363360)?

Addressed

**Comment by 0tuedon** [comment]
Looks good to me, I can't confirm if the Favicon was update, but seems good

**Review by 0tuedon — COMMENTED** [review]
Looks good, seems we have got the update of transcript favicon left. do we wait for tobi's update or just merge that in a later PR?

**Comment by Emmanuel-Develops** [comment]
@IgboPharaoh 
Please rest your branch to staging and cherry-pick the 3 commits added here.
Screenshot 2024-09-30 at 9 46 16 AM

**Pull request merged**
